import axios from 'axios';

// ── Base configuration ───────────────────────────────────────────────────────
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'https://api.kayparts.co/api/';
export const BASE_URL = API_BASE_URL.replace('/api/', '/');
// The uploads disk generates URLs like {APP_URL}/uploads/...
export const ASSETS_BASE_URL = 'https://api.kayparts.co/';

/**
 * Helper to get the correct URL for an asset (brand logo, category image, etc.)
 * Handles absolute URLs from API (generated by Storage::disk('uploads')->url()),
 * relative paths, and provides fallbacks.
 */
export const getAssetUrl = (path) => {
  if (!path) return null;
  if (typeof path !== 'string') return null;
  
  // If it's already an absolute URL
  if (path.startsWith('http')) {
    // Caso especial: La API de Laravel a veces genera URLs con /storage/ 
    // pero en Hostinger estamos usando /uploads/ directamente.
    if (path.includes('api.kayparts.co/storage/')) {
      return path.replace('/storage/', '/uploads/');
    }
    return path;
  }

  // Limpiar la ruta de prefijos duplicados o slash inicial
  let cleanPath = path.trim();
  
  // Si la ruta ya contiene 'uploads/', la limpiamos para no duplicarla
  if (cleanPath.startsWith('uploads/')) {
    cleanPath = cleanPath.slice(8);
  } else if (cleanPath.startsWith('/uploads/')) {
    cleanPath = cleanPath.slice(9);
  } else if (cleanPath.startsWith('/')) {
    cleanPath = cleanPath.slice(1);
  }

  // Si la ruta empieza con 'product_brands/' etc, pero sin el prefijo uploads
  // Se asume que viene de la base de datos como ruta relativa al disco uploads
  return `${ASSETS_BASE_URL}uploads/${cleanPath}`;
};


const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
    'X-Requested-With': 'XMLHttpRequest', // Best practice para Laravel: fuerza retornos JSON en validaciones
  },
  timeout: 15000,
});

// ── Request interceptor: attach Bearer token automatically ───────────────────
api.interceptors.request.use(
  (config) => {
    if (typeof window !== 'undefined') {
      const token = localStorage.getItem('kayparts_token');
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }
    }
    return config;
  },
  (error) => Promise.reject(error)
);

// ── Response interceptor: handle global errors ───────────────────────────────
api.interceptors.response.use(
  (response) => response,
  (error) => {
    const status = error.response?.status;

    // 401 Unauthorized o 419 Page Expired (CSRF) → limpiar sesión y redirigir
    if ((status === 401 || status === 419) && typeof window !== 'undefined') {
      localStorage.removeItem('kayparts_token');
      localStorage.removeItem('kayparts_user');
      // Redirigir solo si no estamos ya en /login
      if (!window.location.pathname.includes('/login')) {
        window.location.href = '/login';
      }
    }

    return Promise.reject(error);
  }
);

export default api;
