name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Cambios en esta rama disparan el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm install

      - name: Build 🏗️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # Subir el contenido de la carpeta de construcción
          branch: deploy # A esta rama
          token: ${{ secrets.GH_TOKEN }} # Token de acceso personal para permisos superiores
          clean: true # Limpia la rama de destino antes de subir
