name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Cambios en esta rama disparan el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ¡ESTO ES LA MAGIA AUTOMÁTICA! Le da permisos al robot sin necesidad del usuario.
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm install

      - name: Build 🏗️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: deploy
          token: ${{ secrets.GITHUB_TOKEN }} # Usa el token automático nativo de GitHub
          clean: true
